// svelte/src/spinner/spinner.svelte
<script>
	import '../../../css/spinner/spinner.css';

	export let color = '';
	export let size = '';
	export let timing = "linear"
	export let format = "no-border"
</script>

<span 
	class="loader loader-spinner {timing} {format}" 
	style="--color: {color}; --size: {size}"
	role="progressbar"
	aria-valuemax="1"
	aria-valuemin="0"
	aria-valuenow="0"
>
	<span class="loader-spinner_background"></span>
	<span class="loader-spinner_spinner"></span>
</span>

// react/src/spinner/spinner.js
import React from 'react';

import '../../../css/spinner/spinner.css';

const Spinner = ({size, color, timing="linear", format="no-border"}) => {
  return (
    <span
      className={`loader loader-spinner ${timing} ${format}`} 
      style={{
        '--size': size,
        '--color': color
      }}
    >
        <span className="loader-spinner_background"></span>
        <span className="loader-spinner_spinner"></span>
    </span>
  )
};

export default Spinner;
