// react/src/bubbles/bubbles.js
import React from 'react';
import '../../../css/bubbles/bubbles.css';

const Bubbles = ({size, color}) => {
  return (
    <span
      className={`loader loader-bubbles`} 
      style={{
        '--size': size,
        '--color': color
      }}
    >
      <span class="loader-bubble_1"></span>
      <span class="loader-bubble_2"></span> 
      <span class="loader-bubble_3"></span> 
    </span>
  )
};

export default Bubbles;

// svelte/src/bubbles/bubbles.svelte
<script>
	import '../../../css/bubbles/bubbles.css';

	export let color = '';
	export let size = '';
</script>

<span 
	class="loader loader-bubbles" 
	style="--color: {color}; --size: {size}"
	role="progressbar"
	aria-valuemax="1"
	aria-valuemin="0"
	aria-valuenow="0"
>
	<span class="loader-bubble_1"></span>
	<span class="loader-bubble_2"></span> 
	<span class="loader-bubble_3"></span> 
</span>
